#!/bin/sh

# get default tty config
stty_default=$(stty -g)

# ensure tty config is restored when exiting
trap 'stty ${stty_default}' EXIT

y_or_n() {
	for arg in "$@"; do
		ARG_NAME=$(printf "%s" "$arg" | cut -d= -f1)
		ARG_VAL=$(printf "%s" "$arg" | cut -d= -f2)
		case $ARG_NAME in
		"--msg")
			MSG="$ARG_VAL"
			;;
		"--default")
			DEFAULT="$ARG_VAL"
			;;
		*)
			continue
			;;
		esac
	done
	case "$DEFAULT" in
	"yes")
		CONFIRMATION_TEXT="[Y/n]"
		;;
	"no")
		CONFIRMATION_TEXT="[y/N]"
		;;
	*)
		CONFIRMATION_TEXT="[y/n]"
		;;
	esac

	while :; do
		printf "%s %s: " "$MSG" "$CONFIRMATION_TEXT"
		read -r yn

		case "$yn" in
		"Y" | "y")
			unset DEFAULT
			return 0
			;;
		"N" | "n")
			unset DEFAULT
			return 1
			;;
		*)
			case "$DEFAULT" in
			"yes")
				yn="y"
				unset DEFAULT
				return 0
				;;
			"no")
				yn="n"
				unset DEFAULT
				return 1
				;;
			*)
				printf "Not a valid response\n"
				continue
				;;
			esac
			;;
		esac
	done
}

_get_hardware_config() {
	if [ -z "$HOST_CONFIG_DIR" ]; then
		printf "\nError: Hardware configuration function called without HOST_CONFIG_DIR being set. This is a bug.\n"
		exit 1
	fi

	HARDWARE_CONFIG="$HOST_CONFIG_DIR/hardware-configuration.nix"
	# nuke old hardware config and regenerate. Its not supposed to be manually modified so assume the user has made no changes to it
	if [ -e "$HARDWARE_CONFIG" ]; then
		rm "$HARDWARE_CONFIG"
	fi

	# generate only the kernel modules and other basic configuration as filesystems are handled by disko
	nixos-generate-config --no-filesystems --root /mnt >/dev/null
	# remove the generated configuration.nix as all we care about is the hardware report
	rm "$CONFIG_ROOT/configuration.nix"

	mv "$CONFIG_ROOT/hardware-configuration.nix" "$HOST_CONFIG_DIR"

	# enable ZramSwap if the host has 4 GB or less RAM
	if [ "$(cat /proc/meminfo | grep MemTotal | cut -d: -f2 | tr -d " kB")" -le 4000000 ]; then
		printf "\nDetected a small amount of available RAM for this host.\n"
		printf "The installer will enable a module for compressed zramSwap to assist with RAM management\n"

		sed -i '$ s/.$//' "$HOST_CONFIG_DIR/configuration.nix"
		printf "zramSwap.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
		printf "}" >>"$HOST_CONFIG_DIR/configuration.nix"
	fi

	# assume that if /tmp/selected-disko-config.nix exists, the formatting process was run for this host and any existing config should be replaced by it
	if [ -e /tmp/selected-disko-config.nix ] && [ -e "$HOST_CONFIG_DIR/disko.nix" ]; then
		rm -f "$HOST_CONFIG_DIR/disko.nix"
	fi

	if [ ! -e "$HOST_CONFIG_DIR/disko.nix" ]; then
		# get the disko file in place.
		if [ ! -e /tmp/selected-disko-config.nix ]; then
			printf "\nERROR: Neither a disko configuration file for this host nor a configuration file generated by the installer could be found.\n"
			printf "This can only happen in very specific scenarios such as rebooting the installer or clearing /tmp before the configuration files could get properly copied.\n"
			printf "Alternatively, it could be caused by a faulty configuration that does not contain a disko.nix\n"
			printf "It can be fixed by reformatting or placing a valid disko file at %s/disko.nix\n" "$HOST_CONFIG_DIR"
			exit 1
		fi
		cp "/tmp/selected-disko-config.nix" "$HOST_CONFIG_DIR/disko.nix" || {
			printf "\nERROR: Failed to copy /tmp/selected-disko-config.nix to %s\n" "$HOST_CONFIG_DIR"
			exit 1
		}
	else
		return 0
	fi
}

_install_nixos() {
	# /tmp will be cleared on bootup if nixos option boot.tmp.cleanOnBoot is set (which it is by default in my config)
	if [ "$(cat /proc/meminfo | grep MemAvailable | cut -d ":" -f2 | tr -d " kB")" -lt 4000000 ] && [ ! -e /mnt/tmp/swap ]; then
		# unless you are installing on a REALLY small drive, this will work fine
		printf "\nWARNING: Detected less than 4GB of free ram\nNixOS requires at least 4GB of free ram to install smoothly.\nCreating a 4GB swap file at /mnt/tmp/swap.\n"
		printf "This file will be cleared upon next bootup and Zram swap will be enabled for this system to ensure it runs smoothly after install.\n"
		mkdir -p /mnt/tmp
		dd if=/dev/zero of=/mnt/tmp/swap bs=1024 count=4000000 || {
			printf "\nError: Unable to create swap file.\n"
			exit 1
		}
		mkswap /mnt/tmp/swap || {
			printf "\nError: Could not use mkswap on that file\n"
			exit 1
		}
		chmod 600 /mnt/tmp/swap
		swapon /mnt/tmp/swap || {
			printf "\nError: Could not activate the swap file with swapon.\n"
			exit 1
		}
	fi

	if [ -n "$APPEND_MODE" ]; then
		# the infamous bug with nix flakes where if the new files are not added to git they cannot be realized to the /nix/store
		git -C "$CONFIG_ROOT" add "$CONFIG_ROOT"
	fi

	if [ ! -d "$HOST_CONFIG_DIR/users" ]; then
		# if no users have been configured, ensure root gets a password
		# This password will not be declaratively stored with sops.
		nixos-install --no-channel-copy --flake "/mnt/etc/nixos#$HOSTNAME" || {
			printf "\nERROR: Installation failed or aborted.\n"
			exit 1
		}
	else
		nixos-install --no-channel-copy --no-root-password --flake "/mnt/etc/nixos#$HOSTNAME" || {
			printf "\nERROR: Installation failed or aborted.\n"
			exit 1
		}
	fi

	exit 0
}

_mv_repo() {
	for file in "$REPO_DIR"/*; do
		mv "$file" "/mnt/etc/nixos"
	done
	rm -rf "$REPO_DIR"
}

_format_disks() {
	if [ -n "$(ls -A /mnt 2>/dev/null)" ]; then
		printf "\nFiles were found in the /mnt directory, which is where your system will be installed.\n"
		printf "If this is due to a failed installation attempt, respond \"No\" and you will not have to format your drives again.\n"
		printf "Otherwise you should abort the installation and clear the directory first to avoid deletion of those files.\n"
		y_or_n --msg="Is your disk mounted already?" --default="yes" && return 0
	fi

	printf "\nThe installer will use a nix-community tool called disko to declaratively partition your hard drives or other persistent storage volumes.\n"
	printf "This allows you to easily store & re-deploy the partition scheme without reliance on nixos-generate-config or partition UUIDs\n"
	printf "By default, this will create a GPT partition table with a FAT partition for the bootloader and an ext4 partition for the OS root filesystem. This is suitable for most scenarios.\n"
	printf "If you wish to deploy a custom setup, such as a dual boot, RAID, or the use of a different filesystem, add the nix file to /etc/disko before you continue.\n"
	printf "The disko repository: https://github.com/nix-community/disko/example has several examples to help you get started.\n"

	if [ -n "$REPO_DIR" ]; then
		printf "Since you have cloned a repository, you will also have the option to select a disko configuration from it to use for formatting.\n"
	fi

	y_or_n --msg="Do you wish to proceed with formatting?" --default="yes" || {
		printf "Aborted\n"
		exit 0
	}

	_failed_disko_condition() {
		[ -z "$SELECTED_DISKO_CONFIG" ] || ! grep -q "disko" "$SELECTED_DISKO_CONFIG"
	}

	if [ "$REPO_DIR" ]; then
		y_or_n --msg="Use a disko file from your repo?" && {
			while :; do
				SELECTED_DISKO_CONFIG=$(fzf --border --border-label-pos 1:bottom --walker-root "$REPO_DIR" --border-label="Choose a disko file to use for formatting. (Press ESC or Ctrl+C to cancel)")
				if _failed_disko_condition; then
					printf "\n"
					y_or_n --msg="No disko file selected, or it is invalid. Do you wish to try again?" || break
				else
					break
				fi
			done
		}
	fi

	DISKO_DEFAULTS_DIR="/etc/disko/defaults"

	if [ -z "$SELECTED_DISKO_CONFIG" ]; then
		CUSTOM_DISKO_CONFIGURATIONS=$(find /etc/disko -type f | sed 's|\/etc\/disko\/||' | grep -v 'defaults')
		if [ "$CUSTOM_DISKO_CONFIGURATIONS" ]; then
			SELECTED_DISKO_CONFIG=$(
				for config in $DISKO_CONFIGURATIONS; do
					# readd the absolute path
					file=/etc/disko/"$config"
					# dirty check to see if the file is actually a disko config
					if grep -q 'disko' "$file"; then
						printf "%s\n" "$config"
					else
						continue
					fi
				done | fzf --disabled --border --border-label-pos 1:bottom --preview='cat /etc/disko/{}' --border-label='Found the following custom configurations. Would you like to use one of these? (Press ESC or Ctrl+C to skip)'
			)
			if [ "$SELECTED_DISKO_CONFIG" ]; then
				SELECTED_DISKO_CONFIG="/etc/disko/""$SELECTED_DISKO_CONFIG"
			else
				printf "\nNo custom disko configuration file selected, proceeding with defaults.\n"
			fi
		fi
	fi

	_remove_password_file() {
		if [ -e "/tmp/secret.key" ]; then
			rm -f "/tmp/secret.key"
		fi
	}

	if [ -z "$SELECTED_DISKO_CONFIG" ]; then
		SELECTED_DISK=$(lsblk -p -do name,label,size,mountpoints | grep -ve "loop0" -e "NAME" -e "nixos-minimal" | fzf --disabled --border --border-label-pos 1:bottom --border-label='Select a disk to install NixOS' | cut -d' ' -f1)

		if [ -z "$SELECTED_DISK" ]; then
			printf "\nNo disk selected\n"
			exit 1
		fi

		printf "Selected Disk: %s\n" "$SELECTED_DISK"

		printf "\nTo protect your storage volume from theft, you have the option to encrypt it with LUKS using a password. (hardware keys are not yet supported)\n"
		y_or_n --msg="Would you like to set up LUKS encryption?" --default="yes" && {
			while :; do
				while [ -z "$PASSWORD" ]; do
					printf "Create Password: "
					stty -echo
					read -r PASSWORD
					stty "$stty_default"
					if [ -z "$PASSWORD" ]; then
						printf "Password cannot be empty.\n"
					fi
				done
				printf "\nRe-enter Password: "
				stty -echo
				read -r PASSWORD2
				stty "$stty_default"
				if [ "$PASSWORD" != "$PASSWORD2" ]; then
					printf "\n\nPasswords do not match! Try again.\n"
				else
					printf "\n"
					break
				fi
			done
			printf "%s" "$PASSWORD" >/tmp/secret.key
			unset PASSWORD PASSWORD2
			LUKS=true
		}

		case "$FIRMWARE" in
		"UEFI")
			if [ "$LUKS" ]; then
				SELECTED_DISKO_CONFIG="$DISKO_DEFAULTS_DIR/luks-uefi-ext4.nix"
			else
				SELECTED_DISKO_CONFIG="$DISKO_DEFAULTS_DIR/uefi-ext4.nix"
			fi
			;;
		"BIOS")
			if [ "$LUKS" ]; then
				SELECTED_DISKO_CONFIG="$DISKO_DEFAULTS_DIR/luks-legacy-ext4.nix"
			else
				SELECTED_DISKO_CONFIG="$DISKO_DEFAULTS_DIR/legacy-ext4.nix"
			fi
			;;
		*)
			printf "Firmware not found, this is a bug\n"
			_remove_password_file
			exit 1
			;;
		esac
	fi

	DISKO_CONFIG_PATH="/tmp/selected-disko-config.nix"

	if [ -e "$DISKO_CONFIG_PATH" ]; then
		rm "$DISKO_CONFIG_PATH"
	fi
	cp "$SELECTED_DISKO_CONFIG" "$DISKO_CONFIG_PATH"

	if [ "$SELECTED_DISK" ]; then
		sed -i "s|device = \"\/dev\/sda\"|device = \"$SELECTED_DISK\"|" "$DISKO_CONFIG_PATH"
	fi

	for file in /mnt/*; do
		rm -rf "$file"
	done

	printf "\nPreparing to format disks.\n"
	# since disko 1.12+ gives a warning about what device its about to destroy, there is no need to implement that here.
	disko --mode destroy,format,mount "$DISKO_CONFIG_PATH" || {
		printf "Error: Disko was unable to format the requested drives\n"
		_remove_password_file
		exit 1
	}

	# cleanup
	unset SELECTED_DISKO_CONFIG
	unset SELECTED_DISK
	_remove_password_file
}

_clone_repo() {
	REPO_DIR=/tmp/nix-config
	if [ -d "$REPO_DIR" ] && [ "$(ls -A "$REPO_DIR")" ]; then
		printf "\nFiles were found in the repo destination directory: %s\n" "$REPO_DIR"
		printf "This only occurs if a previous installation attempt was aborted before the files could be moved.\n"
		y_or_n --msg="Clear the contents of $REPO_DIR and clone your repository again?" || return 0
		rm -rf "$REPO_DIR"
	fi

	mkdir -p "$REPO_DIR"

	while :; do
		printf "Enter the url for your repository: "
		read -r REPO_URL
		git ls-remote "$REPO_URL" || {
			printf "Could not pull repository, Either the url is invalid or you do not have access rights."
			continue
		}
		break
	done

	git clone "$REPO_URL" --depth 1 "$REPO_DIR" || {
		printf "\nSomething went wrong while pulling the repository\n"
		exit 1
	}
}

# main
if [ "$(whoami)" != "root" ]; then
	printf "You must be root.\n"
	exit 1
fi

# sometimes the nix daemon may not be running
if ! systemctl is-active nix-daemon >/dev/null; then
	printf "Nix daemon is not running, starting it.\n"
	systemctl start nix-daemon
fi

# make sure we are connected to the internet
while ! curl -s ifconfig.me >/dev/null; do
	y_or_n --msg="No internet connection detected. Connect Now?" --default="yes" && nmtui
done

printf "\nIf you have used this installer before, you might have already created a configuration for this host.\n"
printf "In this case, assuming you have read access to the remote repository, you can skip directly to the installation phase.\n"
printf "This mode can also be used to repair your system if somehow it cannot boot, even after a rollback.\n"
y_or_n --msg="Install an existing configuration?" --default="no" && {
	_clone_repo
	CONFIGURATIONS="$(nix eval $REPO_DIR'#'nixosConfigurations --apply builtins.attrNames | sed 's/[][]//g' | tr -d '"')"
	# TODO creates one extra newline for some reason
	HOSTNAME=$(printf "%s" "$CONFIGURATIONS" | tr ' ' '\n' | fzf --border --border-label-pos 1:bottom --border-label="Found the following configurations")
	if [ -z "$HOSTNAME" ]; then
		printf "No host was selected.\n"
		exit 0
	fi

	_format_disks

	mkdir -p /mnt/etc/nixos

	_mv_repo
	_get_hardware_config

	printf "\nchecking configuration\n"
	if [ "$(nix eval /mnt/etc/nixos'#'nixosConfigurations."$HOSTNAME".config.sops.secrets)" != "{ }" ]; then
		SOPS_KEYFILE="$(nix eval /mnt/etc/nixos'#'nixosConfigurations."$HOSTNAME".config.sops.age.keyFile | tr -d '"')"
		if [ ! -e "/mnt$SOPS_KEYFILE" ]; then
			printf "\nDetected sops secrets from this configuration.\n"
			printf "You will need to imperatively place your private age key file at /mnt%s before you continue\n" "$SOPS_KEYFILE"
			printf "Press any key to continue..."
			read -r some_key
			unset some_key
		fi

		while [ ! -e "/mnt$SOPS_KEYFILE" ]; do
			printf "Keyfile not found.\nEnsure the file is present in /mnt%s before you continue.\n" "$SOPS_KEYFILE"
			printf "Press any key to continue..."
			read -r some_key
		done
		unset some_key
	fi

	printf "\nChecks complete. No further action needed.\n"
	printf "Installing now.\n"

	_install_nixos
}

printf "\nIf you have used this installer before, you should have an exiting configuration repository.\n"
printf "If you wish, the installer allows you to seamlessly integrate your new configuration with the rest of your NixOS hosts and modules.\n"
y_or_n --msg="Append to your existing repository?" --default="no" && APPEND_MODE=true

# detect hardware
if [ -d /sys/firmware/efi ]; then
	FIRMWARE="UEFI"
else
	FIRMWARE="BIOS"
fi

if lscpu | grep -i "intel" >/dev/null; then
	CPU_VENDOR="intel"
elif lscpu | grep -i "amd" >/dev/null; then
	CPU_VENDOR="amd"
fi

# detect if VM
if lscpu | grep 'Hypervisor vendor:' >/dev/null; then
	QEMU=true
else
	QEMU=false
fi

_check_gpu() {
	if lspci -nn | grep "VGA" | grep -i "$1" >/dev/null; then
		GPU_VENDORS="$GPU_VENDORS""$(printf '"%s" ' "$1")"
	fi
}

_check_gpu "nvidia"
_check_gpu "amd"
_check_gpu "intel"

SYSTEM_ARCH=$(lscpu | grep Arch | tr -d " " | cut -d: -f2)
NIXOS_VERSION=$(nixos-version | cut -d. -f1-2)

_format_disks

# begin writing configuration repository
while :; do
	printf "\nSet your system hostname: "
	read -r HOSTNAME
	# TODO validate hostname
	if [ -z "$HOSTNAME" ]; then
		printf "Hostname cannot be empty.\n"
		continue
	fi
	# if expr "$HOSTNAME"; then
	# 	printf "Hostname can only contain characters [A-Z][a-z][1-9] '-' and '_'. Try again"
	# else
	break
	# fi
done

CONFIG_ROOT="/mnt/etc/nixos"
HOST_CONFIG_DIR="$CONFIG_ROOT/nixosConfigurations/$HOSTNAME"
HOSTS_CONFIG_FILE="$CONFIG_ROOT/nixosConfigurations/default.nix"

y_or_n --msg="Use the default localization configuration? (en_US.UTF-8)" --default="yes" && LOCALE="en_US.UTF-8"
if [ -z "$LOCALE" ]; then
	LOCALE=$(cat /etc/locales.txt | fzf --disabled --border --border-label-pos 1:bottom --border-label="Select the default locale")
	if [ -z "$LOCALE" ]; then
		printf "\nNo localization selected, assuming default.\n"
		LOCALE="en_US.UTF-8"
	else
		LOCALE="$LOCALE"".UTF-8"
	fi
fi

printf "\nChosen Locale: %s\n" "$LOCALE"

y_or_n --msg="Use the default keyboard layout? (US)" --default="yes" && XKB_LAYOUT="us"
if [ -z "$XKB_LAYOUT" ]; then
	XKB_LAYOUT=$(localectl list-keymaps | fzf --disabled --border --border-label-pos 1:bottom --border-label="Select a keyboard layout")
	if [ -z "$XKB_LAYOUT" ]; then
		printf "\nNo layout selected, assuming default (US)\n"
		XKB_LAYOUT="us"
	fi
fi

printf "\nChosen xkb keymap: %s\n" "$XKB_LAYOUT"
printf "Note: This will only apply to window managers under X11 and the Linux Virtual Console.\n"
printf "For wayland compositors like niri or hyprland, you will have to set the keymap in their respective configuration files.\n\n"

y_or_n --msg="Install a desktop envrionment?" --default="yes" && {

	# TODO update this list as more desktops are supported
	KDE_DESCRIPTION="A modern all inclusive desktop environment for wayland.
Very similar to Microsoft Windows 11.
Perfect for beginners."

	NIRI_DESCRIPTION="A high-quality, modern DIY wayland window manager.
Uses infinite scrolling windows in a tiled format.
Recommended for enthusists / advanced users only."

	DESKTOPS="Niri KDE"

	SELECTED_DESKTOP=$(printf "%s\n" "$DESKTOPS" | tr ' ' '\n' | while read -r desktop; do
		printf "%s\n" "$desktop"
	done | fzf --disabled --border --border-label-pos 1:bottom --border-label='Select a desktop environment' --preview "
  if [ {} = 'Niri' ]; then
    printf '$NIRI_DESCRIPTION'
  elif [ {} = 'KDE' ]; then
    printf '$KDE_DESCRIPTION'
  fi
	" | tr '[:upper:]' '[:lower:]')
	if [ -z "$SELECTED_DESKTOP" ]; then
		printf "No desktop selected. Aborting\n"
		exit 1
	fi

	printf "\nDesktop: %s\n\n" "$SELECTED_DESKTOP"
}

printf "NixOS will install with the following configuration.\n"
printf "CPU Brand - %s\n" "$CPU_VENDOR"
if [ -n "$GPU_VENDORS" ]; then
	printf "GPU Brands - $(printf "%s\n" "$GPU_VENDORS" | tr ' ' '\n' | while read -r gpu; do
		printf "%s, " "$gpu"
	done)"
	printf "\n"
fi
printf "Firmware - %s\n" "$FIRMWARE"
printf "System - %s\n" "$SYSTEM_ARCH"
printf "Locale - %s\n" "$LOCALE"
printf "Keyboard - %s\n" "$XKB_LAYOUT"
if [ -n "$SELECTED_DESKTOP" ]; then
	printf "Desktop - %s\n" "$SELECTED_DESKTOP"
fi
printf "NixOS Version - %s\n\n" "$NIXOS_VERSION"

y_or_n --msg="If this is correct, begin writing config to $CONFIG_ROOT?" || {
	printf "Aborted\n"
	exit 1
}

# Implementation

if [ -d "$CONFIG_ROOT" ]; then
	rm -rf "$CONFIG_ROOT"
fi
mkdir -p "$CONFIG_ROOT"

# if the configuration is new
if [ -z "$APPEND_MODE" ]; then
	# flake.nix
	printf " {
			description = \"my NixOS configurations\";

			inputs = {
				# Uncomment to lock your own nixpkgs revision in the flake.lock.
				# Could cause instabilities, use only if you know what you are doing.
				# nixpkgs = {
				#   url = \"github:NixOS/nixpkgs/nixos-unstable\";
				# };

				earthgman = {
					url = \"git+https://git.earthgman.dev/EarthGman/nix-modules\";
					# Be sure to also uncomment this if you use your own nixpkgs input. Mismatched system dependencies are not good.
					# inputs.nixpkgs.follows = \"nixpkgs\";
				};
			};

			outputs = { self, nixpkgs, earthgman, ... }@inputs:
			let
				lib = earthgman.lib; # nixpkgs.lib merged with some custom functions used for modules.
				outputs = self.outputs;
			in
			{
				# expose hosts configured under this flake
				nixosConfigurations = import ./nixosConfigurations { inherit lib inputs outputs; };

				# expose your custom modules.
				nixosModules.default = import ./nixosModules { inherit lib inputs outputs; };

				# expose your overlays (package set modifications)
				overlays = import ./overlays { inherit inputs; };

				# your custom derivations
				packages = 
				let
					supported-systems = [
						# add more system targets if you need.
						\"%s-linux\"
					];
				in
				# generate a package attribute set for each supported architecture
				lib.genAttrs supported-systems (
					system:
					import ./packages {
						pkgs = import nixpkgs {
							config.allowUnfree = true;
							inherit system;
							# give your packages access to your overlays
							overlays = builtins.attrValues outputs.overlays; # transform the set of overlays to a list
						};
					}
				);
			};
		}" "$SYSTEM_ARCH" >$CONFIG_ROOT/flake.nix

	# nixosModules/default.nix
	printf "
    # wrapper for your custom nixosModules
		{ inputs, outputs, lib, ... }:
		{
			pkgs,
			lib,
			config,
			...
		}:
		{
			# automatically wraps up module files present in this directory
			imports = lib.autoImport ./. { } ++ [
				# EXAMPLE
				# inputs.home-manager.nixosModules.default
			];

			# import your overlays to all hosts
			nixpkgs.overlays = builtins.attrValues outputs.overlays;

			# contain and enable your custom modules
			# If you wish to let your modules be consumable by other flakes, be sure to segment them to avoid conflicts.

			# options.your-name-here.enable = lib.mkEnableOption \"your-name-here's NixOS modules\";

			# apply only if your modules are enabled
			# config = lib.mkIf config.your-name-here.enable {
			#   your-name-here.module1.enable = true;
			#   your-name-here.module2.enable = true;
			# };
	}" | install -D /dev/stdin "$CONFIG_ROOT/nixosModules/default.nix"

	# nixosModules/core
	printf "
    # reserved for any modifications you wish to make to the core NixOS module tree from nixpkgs
		{ pkgs, lib, config, ... }:
		{
			imports = lib.autoImport ./. { };
		}" | install -D /dev/stdin "$CONFIG_ROOT/nixosModules/core/default.nix"

	# packages
	printf "
	  # create custom derivations using pkgs.callPackage
		{ pkgs, ... }:
		{
			# my-package = pkgs.callPackage ./my-package.nix { };
		}" | install -D /dev/stdin "$CONFIG_ROOT/packages/default.nix"

	# overlays
	printf "
		# overlays are functions which modify the existing nix package set used by your flake.
		# you can use them to add, remove, or modify packages.
		{ inputs }:
		{
			# add your custom packages
			my-packages = final: prev: import ../packages {
				pkgs = final;
			};

			# example for installing rolling release of a popular project with a flake.nix
			# ghostty-git = inputs.ghostty.overlays.default;
		}" | install -D /dev/stdin "$CONFIG_ROOT/overlays/default.nix"
else
	if [ -z "$REPO_DIR" ]; then
		printf "Error: Repo not found but append mode was sepcified, this is a bug.\n"
		exit 1
	fi

	# get the repo into place
	_mv_repo

	# when appending, if a config for that hostname already exists, replace it
	if [ -d "$HOST_CONFIG_DIR" ]; then
		rm -rf "$HOST_CONFIG_DIR"
	fi
	# TODO need to use sed to remove the host from "$HOSTS_CONFIG_FILE"
fi

# Ask user for preferences
if [ -n "$SELECTED_DESKTOP" ]; then
	y_or_n --msg="Install modules for gaming? (steam, lutris, hardware diagnostic tools, etc?)" --default="no" && GAMING=true
	y_or_n --msg="Install programs for office work? (libreoffice, email client, gimp, etc?)" --default="no" && OFFICE=true
fi
y_or_n --msg="Install penetration and security testing tools from Kali Linux? (nmap, tor-browser, john-the-ripper, wireshark, etc)" --default="no" && HACKER_MODE=true
y_or_n --msg="Install additional nix tools? (recommended for developers)" --default="no" && NIX_TOOLS=true
y_or_n --msg="Would you like to harden your configuration? This disables some features (like password-based ssh authentication) for increased security." --default="yes" && HARDEN=true

# start creation for configuration specific to the host.
mkdir -p "$HOST_CONFIG_DIR"
printf "\nBefore creating your user accounts, you will need to configure sops-nix.\n"
printf "By default, all nix configuration files, including those containing hashed passwords or other secrets, will be world-readable in /nix/store.\n"
printf "To circumvent this security limitation of NixOS, you can use a sops-nix configuration.\n"
printf "This framework allows secure storage of secrets in your configuration repository using encryption.\n"
printf "While other key-based encryption formats can be used for sops-nix. The installer will use age.\n\n"

SOPS_FILE="nixosConfigurations/$HOSTNAME/secrets.yaml"
KEY_FILE_PATH="/mnt/var/lib/sops-nix/keys.txt"
if [ -e "$KEY_FILE_PATH" ]; then
	rm -rf "$KEY_FILE_PATH"
fi
mkdir -p "/mnt/var/lib/sops-nix"

_create_key_alias() {
	while :; do
		printf "\nCreate an alias for your key (\`default\`, \`workstations\`, \`homelab\`, etc): "
		read -r KEY_NAME

		if [ -z "$KEY_NAME" ]; then
			printf "Key name cannot be empty.\n"
			continue
		fi

		if [ "$APPEND_MODE" ]; then
			if cat "$CONFIG_ROOT/.sops.yaml" | grep "&$KEY_NAME"; then
				printf "\nERROR: Detected duplicate key names/aliases in .sops.yaml. Your new key name must be different than your other keys.\n"
			else
				break
			fi
		else
			break
		fi
	done
}

y_or_n --msg="Do you have an exisiting age key pair that you wish to use to encrypt this host's secrets?" --default="no"

case "$yn" in
"Y" | "y")
	printf "Enter your public age key: "
	read -r PUBLIC_AGE_KEY
	_create_key_alias

	while [ ! -e "$KEY_FILE_PATH" ]; do
		printf "Place your private key file at the following location: %s\n" "$KEY_FILE_PATH"
		printf "The file must be in the proper age format or else the install will fail.\n"
		printf "press any key when the file is in place..."
		read -r some_key

		if [ -e "$KEY_FILE_PATH" ]; then
			printf "Key file was not found in the required location.\n"
		fi
	done
	;;
"N" | "n")
	# key generation
	printf "\nGenerating age key-pair...\n"
	age-keygen -o "$KEY_FILE_PATH" >/dev/null || {
		printf "Failed to generate age key pair.\n"
		exit 1
	}
	PUBLIC_AGE_KEY=$(cat "$KEY_FILE_PATH" | grep "public key:" | cut -d ":" -f2 | tr -d " ")

	_create_key_alias

	printf "The generated private key is stored at %s.\n" "$KEY_FILE_PATH"
	printf "It is imperative that you create a backup of this private key after installation is complete. If you lose it, you will no longer be able to access your secrets and your system cannot rebuild.\n"
	printf "press any key to acknowledge..."
	read -r some_key
	unset some_key
	;;
esac

if [ "$APPEND_MODE" ]; then
	# append the key and creation rules to an existing .sops.yaml
	sed -i "/keys:/a\  - &$KEY_NAME $PUBLIC_AGE_KEY" $CONFIG_ROOT/.sops.yaml
	sed -i "/creation_rules:/a\  - path_regex: $SOPS_FILE\n    key_groups:\n      - age:\n          - *$KEY_NAME" $CONFIG_ROOT/.sops.yaml
else
	printf "keys:
  - &%s %s
creation_rules:
  - path_regex: %s
    key_groups:
      - age:
          - *%s" "$KEY_NAME" "$PUBLIC_AGE_KEY" "$SOPS_FILE" "$KEY_NAME" >$CONFIG_ROOT/.sops.yaml
fi

# ensure secure permissions are set
chmod 600 "$KEY_FILE_PATH"

# user creation
printf "\nNow you must add and configure user accounts.\n"
printf "By default, the root user will not be accessible unless configured in this section.\n"
printf "So if you wish to add a method of authentication for root, simply type \`root\` for username.\n"
printf "Otherwise a user with the provided username will be created\n\n"

yn="y"
while [ "$yn" = "Y" ] || [ "$yn" = "y" ]; do
	printf "Username: "
	read -r USERNAME
	# TODO validate username using regex
	if [ -z "$USERNAME" ]; then
		printf "Username cannot be empty.\n"
		continue
	fi

	# TODO make optional and add openssh keys
	# set PASSWORD to some gibberish so the loop can be entered
	PASSWORD="bob"
	while [ "$PASSWORD" != "$PASSWORD2" ]; do
		unset PASSWORD
		while [ -z "$PASSWORD" ]; do
			printf "Password: "
			stty -echo
			read -r PASSWORD
			stty "$stty_default"
			if [ -z "$PASSWORD" ]; then
				printf "Password cannot be empty.\n"
			fi
		done
		printf "\nRe-type Password: "
		stty -echo
		read -r PASSWORD2
		stty "$stty_default"
		if [ "$PASSWORD" != "$PASSWORD2" ]; then
			printf "\n\nPasswords do not match! Try again.\n"
		fi
	done

	if [ "$USERNAME" != "root" ]; then
		NORMAL_USER=true
		y_or_n --msg="Should this user have access to privilege escalation? (such as sudo)" && WHEEL=true
		if [ -n "$SELECTED_DESKTOP" ]; then
			y_or_n --msg="Should this user be allowed to manage network connections?" --default="yes" && NETWORKMANAGER_ADMIN=true
			y_or_n --msg="Should this user be allowed to configure the CUPS printing server?" --default="yes" && CUPS_ADMIN=true
		fi
	fi

	USER_CONFIG_DIR="$HOST_CONFIG_DIR/users/$USERNAME"
	mkdir -p "$USER_CONFIG_DIR"

	printf "{ config, ... }:
    {
			sops.secrets.%s_password.neededForUsers = true;

			users.users.%s = {
				hashedPasswordFile = config.sops.secrets.%s_password.path;
" "$USERNAME" "$USERNAME" "$USERNAME" >"$USER_CONFIG_DIR/default.nix"

	if [ "$NORMAL_USER" ]; then
		printf "isNormalUser = true;\n" >>"$USER_CONFIG_DIR/default.nix"
	fi

	EXTRAGROUPS=''
	if [ "$WHEEL" ]; then
		EXTRAGROUPS="$EXTRAGROUPS"'"wheel"'
	fi
	if [ "$NETWORKMANAGER_ADMIN" ]; then
		EXTRAGROUPS="$EXTRAGROUPS"'"networkmanager"'
	fi
	if [ "$CUPS_ADMIN" ]; then
		EXTRAGROUPS="$EXTRAGROUPS"'"lpadmin"'
	fi

	if [ -n "$EXTRAGROUPS" ]; then
		printf "extraGroups = [ " >>"$USER_CONFIG_DIR/default.nix"
		printf "%s\n" "$EXTRAGROUPS" | tr ' ' '\n' | while read -r group; do
			printf '%s ' "$group" >>"$USER_CONFIG_DIR/default.nix"
		done
		printf "];" >>"$USER_CONFIG_DIR/default.nix"
	fi

	printf '};
}' >>"$USER_CONFIG_DIR/default.nix"

	printf "%s_password: %s" "$USERNAME" "$(mkpasswd -s "$PASSWORD")" >>"$HOST_CONFIG_DIR/secrets.yaml"
	USERS="$USERS""$USERNAME "

	# make sure variables are cleared for the next user
	unset USERNAME
	unset PASSWORD
	unset PASSWORD2
	unset NORMAL_USER
	unset NETWORKMANAGER_ADMIN
	unset AUTHENTICATION_METHOD
	unset AUTHENTICATION_METHODS
	unset WHEEL
	unset CUPS_ADMIN

	y_or_n --msg="Add/Configure another user?" --default="no"
done

if [ -e "$CONFIG_ROOT/$SOPS_FILE" ]; then
	sops --config "$CONFIG_ROOT/.sops.yaml" -e -i "$CONFIG_ROOT/$SOPS_FILE" || {
		printf "Failed to encrypt secrets for this host.\n"
		exit 1
	}
fi

# create configuration.nix
printf '{ pkgs, lib, config, ... }:
		{
			imports = [
				# kernel configuration from nixos-generate-config
				./hardware-configuration.nix
				# fstab config using disko modules
				./disko.nix
				# your installed applications and programs
				./programs
				# services this machine is hosting
				./services
				# add users
				] ++ (lib.optionals (builtins.pathExists ./users) lib.autoImport ./users { });

			i18n.defaultLocale = "%s";
			services.xserver.xkb.layout = "%s";' \
	"$LOCALE" "$XKB_LAYOUT" >"$HOST_CONFIG_DIR/configuration.nix"

# add optional modules
if [ -n "$GAMING" ]; then
	printf "earthgman.profiles.gaming.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
fi
if [ -n "$OFFICE" ]; then
	printf "earthgman.profiles.office.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
fi
if [ -n "$HACKER_MODE" ]; then
	printf "earthgman.profiles.hacker-mode.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
fi
if [ -n "$NIX_TOOLS" ]; then
	printf "earthgman.profiles.nix-tools.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
fi
if [ -n "$HARDEN" ]; then
	printf "earthgman.profiles.harden.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
fi
printf '}' >>"$HOST_CONFIG_DIR/configuration.nix"

# create split host config (programs, services)
printf "{pkgs, lib, config, ... }:
{
  programs = { };
}" | install -D /dev/stdin "$HOST_CONFIG_DIR/programs/default.nix"

printf "{pkgs, lib, config, ... }:
{
  services = { };
}" | install -D /dev/stdin "$HOST_CONFIG_DIR/services/default.nix"

# write new host to the global hosts configuration file
if [ "$APPEND_MODE" ]; then
	# with "append" remove the last character to make way for the new configuration
	sed -i '$ s/.$//' "$HOSTS_CONFIG_FILE"
else
	# add the function header if this is a new configuration
	printf "{ lib, inputs, outputs, ... }:
		{\n" >"$HOSTS_CONFIG_FILE"
fi

printf '%s = lib.mkNixosHost {
	hostname = "%s";
	cpu-vendor = "%s";
	gpu-vendors = [ %s ];
	firmware = "%s";
	isQemu = %s;
	%s
	configuration = ./%s/configuration.nix;
	sopsFile = ./%s/secrets.yaml;
	specialArgs = { inherit inputs; };
	modules = [ outputs.nixosModules.default ];
	stateVersion = "%s";
};' \
	"$HOSTNAME" \
	"$HOSTNAME" \
	"$CPU_VENDOR" \
	"$(printf "%s" "$GPU_VENDORS" | tr ' ' '\n' | while read -r gpu; do
		printf "%s " "$gpu"
	done)" \
	"$FIRMWARE" \
	"$QEMU" \
	"$(if [ -n "$SELECTED_DESKTOP" ]; then
		printf 'desktop = "%s";' "$SELECTED_DESKTOP"
	else
		printf 'desktop = null;'
	fi)" \
	"$HOSTNAME" \
	"$HOSTNAME" \
	"$NIXOS_VERSION" >>"$HOSTS_CONFIG_FILE"

printf "\n}" >>"$HOSTS_CONFIG_FILE"

_get_hardware_config
# custom script to recursively format all nix files
nixfmt.sh "$CONFIG_ROOT"

_install_nixos
