#!/usr/bin/env bash

clear

if [ "$(whoami)" != "root" ]; then
	printf "You must be root.\n"
	exit 1
fi

# ensure that the nix daemon is running
if ! systemctl is-active nix-daemon >/dev/null; then
	printf "Nix daemon is not running, starting it.\n"
	systemctl start nix-daemon
fi

y_or_n() {
	for arg in "$@"; do
		ARG_NAME=$(printf "%s" "$arg" | cut -d= -f1)
		ARG_VAL=$(printf "%s" "$arg" | cut -d= -f2)
		case $ARG_NAME in
		"--msg")
			MSG="$ARG_VAL"
			;;
		"--default")
			DEFAULT="$ARG_VAL"
			;;
		*)
			continue
			;;
		esac
	done
	case "$DEFAULT" in
	"yes")
		CONFIRMATION_TEXT="[Y/n]"
		;;
	"no")
		CONFIRMATION_TEXT="[y/N]"
		;;
	*)
		CONFIRMATION_TEXT="[y/n]"
		;;
	esac

	while :; do
		printf "%s %s: " "$MSG" "$CONFIRMATION_TEXT"
		read -r yn

		case "$yn" in
		"Y" | "y")
			unset DEFAULT
			return 0
			;;
		"N" | "n")
			unset DEFAULT
			return 1
			;;
		*)
			case "$DEFAULT" in
			"yes")
				yn="y"
				unset DEFAULT
				return 0
				;;
			"no")
				yn="n"
				unset DEFAULT
				return 1
				;;
			*)
				printf "Not a valid response\n"
				continue
				;;
			esac
			;;
		esac
	done
}

# make sure the host is connected to the internet
while ! curl -s ifconfig.me >/dev/null; do
	y_or_n --msg="No internet connection detected. Connect Now?" --default="yes"
	case "$?" in
	0)
		nmtui
		clear
		;;
	*)
		printf "Aborted.\n"
		exit 1
		;;
	esac
done

_clone_repo() {
	REPO_DIR=/tmp/your-snowglobe
	if [ -d "$REPO_DIR" ] && [ "$(ls -A "$REPO_DIR")" ]; then
		printf "\nFiles were found in the repo destination directory: %s\n" "$REPO_DIR"
		printf "This only occurs if a previous installation attempt was aborted before the files could be moved.\n"
		y_or_n --msg="Clear the contents of $REPO_DIR and clone your repository again?" --default="no" || return 0
		rm -rf "$REPO_DIR"
	fi

	mkdir -p "$REPO_DIR"

	while :; do
		printf "Enter the url for your repository: "
		read -r REPO_URL
		git ls-remote "$REPO_URL" || {
			printf "Could not pull repository, Either the url is invalid or you do not have access rights.\n"
			continue
		}
		break
	done

	git clone "$REPO_URL" --depth 1 "$REPO_DIR" || {
		printf "\nSomething went wrong while pulling the repository\n"
		exit 1
	}
}

_mv_repo() {
	for file in $(ls -A "$REPO_DIR"); do
		mv "$REPO_DIR/$file" "/mnt/etc/nixos"
	done
}

_get_hardware_info() {
	if [ -d /sys/firmware/efi ]; then
		FIRMWARE="UEFI"
	else
		FIRMWARE="BIOS"
	fi

	if lscpu | grep -i "intel" >/dev/null; then
		CPU_VENDOR="intel"
	elif lscpu | grep -i "amd" >/dev/null; then
		CPU_VENDOR="amd"
	else
		CPU_VENDOR="unknown"
	fi

	if lscpu | grep 'Hypervisor vendor:' >/dev/null; then
		IS_VM=true
	else
		IS_VM=false
	fi

	GPU_VENDORS=()
	_check_gpu_vendor() {
		if lspci -nn | grep "VGA" | grep -i "$1" >/dev/null; then
			GPU_VENDORS+=("$1")
		fi
	}
	_check_gpu_vendor "nvidia"
	_check_gpu_vendor "amd"
	_check_gpu_vendor "intel"

	CPU_ARCH=$(lscpu | grep Arch | tr -d " " | cut -d: -f2)
	NIXOS_VERSION=$(nixos-version | cut -d. -f1-2)
}

_get_nixos_hardware_config() {
	if [ -z "$HOST_CONFIG_DIR" ]; then
		printf "\nError: Hardware configuration function called without HOST_CONFIG_DIR being set. This is a bug.\n"
		exit 1
	fi

	HARDWARE_CONFIG="$HOST_CONFIG_DIR/hardware-configuration.nix"
	# nuke old hardware config and regenerate. Its not supposed to be manually modified so assume the user has made no changes to it
	if [ -e "$HARDWARE_CONFIG" ]; then
		rm "$HARDWARE_CONFIG"
	fi

	# generate only the kernel modules and other basic configuration as filesystems are handled by disko
	nixos-generate-config --no-filesystems --root /mnt >/dev/null
	# remove the generated configuration.nix as all we care about is the hardware report
	rm "$CONFIG_ROOT/configuration.nix"

	mv "$CONFIG_ROOT/hardware-configuration.nix" "$HOST_CONFIG_DIR"

	# enable ZramSwap if the host has 4 GB or less RAM
	if [ "$(cat /proc/meminfo | grep MemTotal | cut -d: -f2 | tr -d " kB")" -le 4000000 ]; then
		printf "\nDetected a small amount of available RAM for this host.\n"
		printf "The installer will enable a module for compressed zramSwap to assist with RAM management\n"

		sed -i '$ s/.$//' "$HOST_CONFIG_DIR/configuration.nix"
		printf "zramSwap.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
		printf "}" >>"$HOST_CONFIG_DIR/configuration.nix"
	fi

	# assume that if /tmp/selected-disko-config.nix exists, the formatting process was run for this host and any existing config should be replaced by it
	if [ -e /tmp/selected-disko-config.nix ] && [ -e "$HOST_CONFIG_DIR/disko.nix" ]; then
		rm -f "$HOST_CONFIG_DIR/disko.nix"
	fi

	if [ ! -e "$HOST_CONFIG_DIR/disko.nix" ]; then
		# get the disko file in place.
		if [ ! -e /tmp/selected-disko-config.nix ]; then
			printf "\nERROR: Neither a disko configuration file for this host nor a configuration file generated by the installer could be found.\n"
			printf "This can only happen in very specific scenarios such as rebooting the installer or clearing /tmp before the configuration files could get properly copied.\n"
			printf "It can be fixed by reformatting or placing a valid disko file at %s/disko.nix\n" "$HOST_CONFIG_DIR"
			exit 1
		fi
		cp "/tmp/selected-disko-config.nix" "$HOST_CONFIG_DIR/disko.nix" || {
			printf "\nERROR: Failed to copy /tmp/selected-disko-config.nix to %s\n" "$HOST_CONFIG_DIR"
			exit 1
		}
	else
		return 0
	fi

}

_get_disk_info() {
	DISK_PATH=$1
	printf "Associated Serials\n"
	printf "__________________\n\n"
	for serial in $(ls -A /dev/disk/by-id); do
		if [ "$(readlink -f "/dev/disk/by-id/$serial")" = "$DISK_PATH" ]; then
			printf "%s\n" "$serial"
		fi
	done
	printf "\n\nBlock-Device contents\n"
	printf "____________________\n\n"
	lsblk -f "$DISK_PATH"
}
# export is required for sub-processes, such as fzf's preview to see the custom function
export -f _get_disk_info

_select_disk() {
	FZF_PROMPT="$1"

	while :; do
		SELECTED_DISK=$(
			# prevent unwriteable cdrom of loop devices from appearing
			for disk in $(lsblk -do name | grep -ve NAME -e 'sr' -e 'loop'); do
				DEVICE_PATH="/dev/$disk"
				printf "%s\n" "$DEVICE_PATH"
			done |
				fzf --border \
					--border-label-pos 1:top \
					--reverse \
					--border-label="$FZF_PROMPT" \
					--preview='bash -c "_get_disk_info {}"' \
					--preview-window 'right,75%,border-left'
		)

		if [ -z "$SELECTED_DISK" ]; then
			y_or_n --msg="No disk was selected. Would you like to abort the installation" --default="no" && {
				printf "Aborted\n"
				exit 1
			}
		else
			printf "Selected Disk: %s\n" "$SELECTED_DISK"
			break
		fi
	done
}

_format_disks() {
	DISKO_CONFIG_PATH="/tmp/selected-disko-config.nix"
	# edge case where it is unknown what is mounted so the user's input is required
	if [ -n "$(ls -A /mnt 2>/dev/null)" ]; then
		printf "\nFiles were found in the /mnt directory, which is where your system will be installed.\n"
		printf "This could be due to a mounted drive or a failed installation attempt.\n"
		printf "If this is due to a failed installation, you will not have to format the disks again.\n"
		printf "Otherwise, you should abort the installation and ensure that the disk is unmounted to prevent deletion of files.\n"
		y_or_n --msg="Do you wish to skip formatting?" --default="yes" && return 0
	fi

	printf "\nThe installer will use a nix-community tool, disko, to declaratively configure partitions for your hard drives or persistent storage volumes.\n"
	printf "By default, this will create a GPT partition table with a FAT partition for the bootloader and an ext4 partition for the OS root filesystem. This is suitable for most scenarios.\n\n"

	printf "If you wish to deploy a custom setup, such as a dual boot, RAID, or the use of a different filesystem, add the nix file to /etc/disko before you continue.\n"
	printf "Note: These setups are very customizable and are for enthusists / advanced users only, so these will not be included by default.\n"
	printf "For reference, the disko repository: https://github.com/nix-community/disko/example has several examples to help you get started.\n\n"

	if [ "$REPO_DIR" ]; then
		printf "Since you have cloned an existing snowglobe repository, you also have the option to deploy a disko file from there instead.\n\n"
	fi

	y_or_n --msg="Do you wish to proceed with formatting?" --default="yes" || {
		printf "Aborted\n"
		exit 1
	}

	_failed_disko_condition() {
		# will try its best detect whether the selected file is actually a disko file or is a bogus nix file
		# It is totally possible however for this to fail depending on the file selected
		# This is kind of unlikely so I will just ignore it as it works in most cases
		[ -z "$SELECTED_DISKO_CONFIG" ] || [ ! -f "$SELECTED_DISKO_CONFIG" ] || ! grep -q "disko" "$SELECTED_DISKO_CONFIG"
	}

	if [ "$REPO_DIR" ]; then
		y_or_n --msg="Use a disko file from your repo?" && {
			while :; do
				SELECTED_DISKO_CONFIG=$(fzf \
					--preview 'bat -f {}' \
					--border --border-label-pos 1:bottom \
					--walker-root "$REPO_DIR" \
					--border-label="Choose a disko file to use for formatting. (Press ESC or Ctrl+C to cancel)")
				if _failed_disko_condition; then
					printf "\n"
					y_or_n --msg="No disko file was selected. Or, it is invalid. Do you wish to try another file from your repo?" || break
				else
					CUSTOM_DISKO=true
					break
				fi
			done
			if _failed_disko_condition; then
				y_or_n --msg="Would you like to continue by using other disko formatting methods?" --default="yes" || {
					printf "Aborted\n"
					exit 1
				}
			fi
		}
	fi

	if [ -z "$CUSTOM_DISKO" ]; then
		CUSTOM_DISKO_CONFIGURATIONS=$(find /etc/disko -type f | sed 's|\/etc\/disko\/||' | grep -v 'defaults')
		if [ "$CUSTOM_DISKO_CONFIGURATIONS" ]; then
			SELECTED_DISKO_CONFIG=$(
				for config in $CUSTOM_DISKO_CONFIGURATIONS; do
					# readd the absolute path
					file="/etc/disko/$config"
					# dirty check to see if the file is actually a disko config
					if grep -q 'disko' "$file"; then
						printf "%s\n" "$config"
					else
						continue
					fi
				done | fzf \
					--disabled \
					--border \
					--border-label-pos 1:bottom \
					--preview='bat -f /etc/disko/{}' \
					--border-label='Found the following custom configurations. Would you like to use one of these? (Press ESC or Ctrl+C to skip)'
			)
			if [ "$SELECTED_DISKO_CONFIG" ]; then
				SELECTED_DISKO_CONFIG="/etc/disko/""$SELECTED_DISKO_CONFIG"
				CUSTOM_DISKO=true
			else
				printf "\nNo custom disko configuration file selected, proceeding with defaults.\n"
			fi
		fi
	fi

	# default disko deployment
	if [ -z "$CUSTOM_DISKO" ]; then
		DISKO_DEFAULTS_DIR="/etc/disko/defaults"

		_select_disk "Select a disk to install NixOS"

		printf "\nTo protect your persistent storage volume from theft, you can use the Linux Unified Key Setup (LUKS) to encrypt it\n"
		printf "By default the installer will set up a passphrase that you will have to enter to boot.\n"
		y_or_n --msg="Would you like to set up LUKS encryption?" --default="no" && {
			printf "\nYou will now be prompted for a passphrase to encrypt your disk.\n"
			printf "For the greatest level of security you should ensure the following:\n"
			printf "	1. Your password should be different than any used for websites or services.\n"
			printf "	2. Easy to remember. If you lose this password you will never be able to recover your files.\n"
			printf "	3. Moderately sized (recommended is between 15-25 characters).\n"
			while [ -z "$PASSWORD" ] || [ "$PASSWORD" != "$PASSWORD2" ]; do
				printf "\n"
				read -rs -p "Enter Password: " PASSWORD
				if [ -z "$PASSWORD" ]; then
					continue
				fi

				printf "\n"
				read -rs -p "Confirm Password: " PASSWORD2
				printf "\n"
				if [ "$PASSWORD" != "$PASSWORD2" ]; then
					printf "\nPasswords do not match! Try again.\n"
				else
					printf "\n"
					break
				fi
			done
			printf "%s" "$PASSWORD" >/tmp/luks-password
			unset PASSWORD PASSWORD2
			LUKS=true
		}

		if [ "$LUKS" ]; then
			SELECTED_DISKO_CONFIG="$DISKO_DEFAULTS_DIR/default-ext4-luks.nix"
		else
			SELECTED_DISKO_CONFIG="$DISKO_DEFAULTS_DIR/default-ext4.nix"
		fi

		cat "$SELECTED_DISKO_CONFIG" >"$DISKO_CONFIG_PATH"

		if [ "$SELECTED_DISK" ]; then
			# capture the persistent serial name of the disk for the disko file
			for serial in $(ls -A /dev/disk/by-id); do
				if [ "$(readlink -f "/dev/disk/by-id/$serial")" = "$SELECTED_DISK" ]; then
					ASSOCIATED_DISK_SERIAL="$serial"
					break
				fi
			done
			sed -i "s|device = \"\/dev\/sda\"|device = \"\/dev\/disk\/by-id\/$ASSOCIATED_DISK_SERIAL\"|" "$DISKO_CONFIG_PATH"
		fi

		# will nuke any file in /mnt
		# the user has already been asked about this so just go ahead and do it
		for file in /mnt/*; do
			rm -rf "$file"
		done

		disko --mode destroy,format,mount "$DISKO_CONFIG_PATH" || {
			printf "Error: Disko was unable to format the request drives\n"
			DISKO_ERROR=true
		}

		# cleanup
		unset SELECTED_DISKO_CONFIG
		unset SELECTED_DISK
		if [ -e "/tmp/luks-password" ]; then
			rm "/tmp/luks-password"
		fi

		if [ "$DISKO_ERROR" ]; then
			exit 1
		fi
	fi
}

_install_nixos() {
	# /tmp will be cleared on bootup if nixos option boot.tmp.cleanOnBoot is set (which it is by default in my config)
	if [ "$(cat /proc/meminfo | grep MemAvailable | cut -d ":" -f2 | tr -d " kB")" -lt 4000000 ] && [ ! -e /mnt/tmp/swap ]; then
		# unless you are installing on a REALLY small drive, this will work fine
		printf "\nWARNING: Detected less than 4GB of free ram\nNixOS requires at least 4GB of free ram to install smoothly.\nCreating a 4GB swap file at /mnt/tmp/swap.\n"
		printf "This file will be cleared upon next bootup and Zram swap will be enabled for this system to ensure it runs smoothly after install.\n"
		mkdir -p /mnt/tmp
		dd if=/dev/zero of=/mnt/tmp/swap bs=1024 count=4000000 || {
			printf "\nError: Unable to create swap file.\n"
			exit 1
		}
		mkswap /mnt/tmp/swap || {
			printf "\nError: Could not use mkswap on that file\n"
			exit 1
		}
		chmod 600 /mnt/tmp/swap
		swapon /mnt/tmp/swap || {
			printf "\nError: Could not activate the swap file with swapon.\n"
			exit 1
		}
	fi

	if [ -n "$APPEND_MODE" ]; then
		# the infamous bug with nix flakes where if the new files are not added to git they cannot be realized to the /nix/store
		git -C "$CONFIG_ROOT" add "$CONFIG_ROOT"
	fi

	if [ ! -d "$HOST_CONFIG_DIR/users" ]; then
		# if no users have been configured, ensure root gets a password
		# This password will not be declaratively stored with sops.
		nixos-install --no-channel-copy --flake "/mnt/etc/nixos#$HOSTNAME" || {
			printf "\nERROR: Installation failed or aborted.\n"
			exit 1
		}
	else
		nixos-install --no-channel-copy --no-root-password --flake "/mnt/etc/nixos#$HOSTNAME" || {
			printf "\nERROR: Installation failed or aborted.\n"
			exit 1
		}
	fi

	# end of script
	exit 0
}

# main
CONFIG_ROOT="/mnt/etc/nixos"

printf "\nIf you have used the installer before, you might have already created a configuration for this host.\n"
printf "Assuming you have read access to the remote repository, you can skip directly to the installation phase.\n"
printf "You can also use this mode to auto-detect and propagate hardware changes (such changes to disk layouts or gpu vendor) to your configuration.\n\n"

y_or_n --msg="Install an existing configuration?" --default="no" && {
	_clone_repo
	unset HOSTNAME
	while [ -z "$HOSTNAME" ]; do
		CONFIGURATIONS=$(nix eval $REPO_DIR'#'nixosConfigurations --apply builtins.attrNames | sed 's/[][]//g' | tr -d '"')
		HOSTNAME="$(for config in $CONFIGURATIONS; do
			printf "%s\n" "$config"
		done | fzf \
			--border \
			--border-label-pos 1:bottom \
			--border-label="Found the following configurations. Which would you like to install?")"
		if [ -z "$HOSTNAME" ]; then
			printf "\nNo host was selected\n"
			y_or_n --msg="Would you like to try the selection again?" --default="yes" || {
				print "Aborted"
				exit 1
			}
		fi
	done

	printf "\nSelected Host: %s\n" "$HOSTNAME"

	# TODO add hardware regeneration mode
	_format_disks
	mkdir -p "$CONFIG_ROOT"

	HOST_CONFIG_DIR="$CONFIG_ROOT/nixosConfigurations/$HOSTNAME"
	_mv_repo
	_get_nixos_hardware_config

	printf "\nchecking configuration\n"
	if [ "$(nix eval /mnt/etc/nixos'#'nixosConfigurations."$HOSTNAME".config.sops.secrets)" != "{ }" ]; then
		SOPS_KEYFILE="$(nix eval /mnt/etc/nixos'#'nixosConfigurations."$HOSTNAME".config.sops.age.keyFile | tr -d '"')"
		if [ ! -e "/mnt$SOPS_KEYFILE" ]; then
			printf "\nDetected sops secrets from this configuration.\n"
			printf "You will need to imperatively place your private age key file at /mnt%s before you continue\n" "$SOPS_KEYFILE"
			printf "Press any key to continue..."
			read -r some_key
			unset some_key
		fi

		while [ ! -e "/mnt$SOPS_KEYFILE" ]; do
			printf "Keyfile not found.\nEnsure the file is present in /mnt%s before you continue.\n" "$SOPS_KEYFILE"
			printf "Press any key to continue..."
			read -r some_key
		done
		unset some_key
	fi

	printf "\nChecks complete. No further action needed.\n"
	printf "Installing now.\n"

	_install_nixos
}

printf "\nIf you have used this installer before, you should have an exiting configuration repository.\n"
printf "If you wish, the installer allows you to seamlessly integrate your new configuration with the rest of your NixOS hosts and modules.\n"
y_or_n --msg="Append to your existing repository?" --default="no" && {
	APPEND_MODE=true
	_clone_repo
}

_format_disks

# Gather various information from the user
_set_hostname() {
	printf "Note: Hostname will be cleansed of characters that are not [a-z][A-Z][0-9], -, or _\n"
	while :; do
		read -rp "Set your system hostname: " HOSTNAME
		if [ -z "$HOSTNAME" ]; then
			printf "Hostname cannot be empty.\n"
			continue
		fi
		break
	done

	# trim problematic characters from the hostname
	HOSTNAME=$(printf "%s" "$HOSTNAME" | tr -d '[`"=$%#^<>+(){}*!&[]~|][:blank:][:cntrl:]')

	HOST_CONFIG_DIR="$CONFIG_ROOT/nixosConfigurations/$HOSTNAME"
	HOSTS_CONFIG_FILE="$CONFIG_ROOT/nixosConfigurations/default.nix"
}

clear
printf "\nNote: for the next few steps, if you happen to enter information incorrectly, you do not have to abort.\n"
printf "The installer will let you modify any configuration before installing.\n\n"

_set_hostname

mkdir -p "$CONFIG_ROOT"

_select_locale() {
	unset LOCALE
	y_or_n --msg="Use the default localization configuration? (en_US.UTF-8)" --default="yes" && LOCALE="en_US.UTF-8"
	if [ -z "$LOCALE" ]; then
		LOCALE=$(cat /etc/locales.txt | fzf \
			--border \
			--border-label-pos 1:bottom \
			--border-label="Select the default locale")
		if [ -z "$LOCALE" ]; then
			printf "\nNo localization selected, assuming default.\n"
			LOCALE="en_US.UTF-8"
		else
			LOCALE="$LOCALE"".UTF-8"
		fi
	fi
}

_select_xkb_layout() {
	unset XKB_LAYOUT
	y_or_n --msg="Use the default keyboard layout? (US)" --default="yes" && XKB_LAYOUT="us"
	if [ -z "$XKB_LAYOUT" ]; then
		XKB_LAYOUT=$(localectl list-keymaps | fzf \
			--border \
			--border-label-pos 1:bottom \
			--border-label="Select a keyboard layout")
		if [ -z "$XKB_LAYOUT" ]; then
			printf "\nNo layout selected, assuming default (US)\n"
			XKB_LAYOUT="us"
		fi
	fi

	printf "\nWarning: The selected layout will only apply to window managers using the xserver and the Linux Virtual Console.\n"
	printf "For Wayland compositors like Niri or Hyprland, you will have to set the keymap in their respective configuration files.\n\n"
}

_select_desktop_environment() {
	unset SELECTED_DESKTOP
	y_or_n --msg="Install a desktop envrionment?" --default="yes" && {

		KDE_DESCRIPTION="A modern all inclusive desktop environment for wayland.
Very similar to Microsoft Windows 11.
Perfect for beginners."

		NIRI_DESCRIPTION="A high-quality, modern DIY wayland window manager.
Uses infinite scrolling windows in a tiled format.
Recommended for enthusists / advanced users only."

		# TODO support some more desktops
		DESKTOPS=("Niri" "KDE")

		while [ -z "$SELECTED_DESKTOP" ]; do
			SELECTED_DESKTOP=$(
				for desktop in "${DESKTOPS[@]}"; do
					printf "%s\n" "$desktop"
				done | fzf \
					--disabled \
					--border \
					--reverse \
					--border-label-pos 1:top \
					--border-label='Select a desktop environment' \
					--preview-window 'right,75%,border-left' \
					--preview "
  if [ {} = 'Niri' ]; then
    printf '$NIRI_DESCRIPTION'
  elif [ {} = 'KDE' ]; then
    printf '$KDE_DESCRIPTION'
  fi
	" | tr '[:upper:]' '[:lower:]'
			)
			if [ -z "$SELECTED_DESKTOP" ]; then
				y_or_n --msg="No desktop selected. Would you like to try again?" --default="yes" || {
					printf "No desktop environment will be installed\n"
					break
				}
			fi
			break
		done
	}
}

_select_optional_profiles() {
	ENABLED_PROFILES=()
	if [ -n "$SELECTED_DESKTOP" ]; then
		y_or_n --msg="Install modules for gaming? (steam, lutris, hardware diagnostic tools, etc?)" --default="no" && ENABLED_PROFILES+=("Gaming")
		y_or_n --msg="Install programs for office work? (libreoffice, email client, gimp, etc?)" --default="no" && ENABLED_PROFILES+=("Office")
	fi
	y_or_n --msg="Install penetration and security testing tools from Kali Linux? (nmap, tor-browser, john-the-ripper, wireshark, etc)" --default="no" && ENABLED_PROFILES+=("Hacking-Tools")
	y_or_n --msg="Install additional nix tools? (recommended for developers)" --default="no" && ENABLED_PROFILES+=("Nix-Tools")
	y_or_n --msg="Would you like to harden your configuration? This disables some features (like password-based ssh authentication) for increased security." --default="yes" && ENABLED_PROFILES+=("Harden")
}

_get_hardware_info

_select_locale
_select_xkb_layout
_select_desktop_environment
_select_optional_profiles

while :; do
	clear
	printf "Your host will be installed with the following configuration:\n"

	printf "\nDetected Hardware Configuration:\n"
	printf "CPU Brand - %s\n" "$CPU_VENDOR"
	if [ ${#GPU_VENDORS[@]} -gt 0 ]; then
		printf "GPU Brands - %s\n" "${GPU_VENDORS[@]}"
	fi
	printf "Firmware - %s\n" "$FIRMWARE"
	printf "CPU Arch - %s\n" "$CPU_ARCH"

	printf "\nNixOS Information\n"
	printf "Version - %s\n" "$NIXOS_VERSION"

	printf "\nUser-selected preferences and system identifiers:\n"
	printf "Hostname - %s\n" "$HOSTNAME"
	printf "Locale - %s\n" "$LOCALE"
	printf "Keyboard Layout - %s\n" "$XKB_LAYOUT"
	if [ -z "$SELECTED_DESKTOP" ]; then
		printf "Desktop - None\n"
	else
		printf "Desktop - %s\n" "$SELECTED_DESKTOP"
	fi
	if [ ${#ENABLED_PROFILES[@]} -gt 0 ]; then
		printf "Optional profile - %s\n" "${ENABLED_PROFILES[@]}"
	fi

	printf "\n"

	y_or_n --msg="Are you satisfied with the current configuration?" --default="yes" && break
	clear
	OPTIONS=("Hostname" "Desktop" "Locale" "Keyboard Layout" "Optional Profiles")
	SELECTED="$(for option in "${OPTIONS[@]}"; do
		printf "%s\n" "$option"
	done | fzf \
		--disabled \
		--border \
		--border-label-pos 1:bottom \
		--border-label="Which do you wish to change? (Press esc or Ctrl+C to continue)")"
	case "$SELECTED" in
	"Hostname")
		_set_hostname
		;;
	"Desktop")
		_select_desktop_environment
		;;
	"Locale")
		_select_locale
		;;
	"Keyboard Layout")
		_select_xkb_layout
		;;
	"Optional Profiles")
		_select_optional_profiles
		;;
	*)
		continue
		;;
	esac
done

# Begin config write
if [ -d "$CONFIG_ROOT" ]; then
	rm -rf "$CONFIG_ROOT"
fi
mkdir -p "$CONFIG_ROOT"

# if the configuration is new
if [ -z "$APPEND_MODE" ]; then
	# flake.nix
	printf " {
			description = \"my NixOS configurations\";

			inputs = {
				nixpkgs.follows = \"snowglobe-core/nixpkgs\";
				# Uncomment to lock your own nixpkgs revision in the flake.lock.
				# Could cause instabilities, use only if you know what you are doing.
				# nixpkgs = {
				#   url = \"github:NixOS/nixpkgs/nixos-unstable\";
				# };

				snowglobe-core = {
					url = \"git+https://git.earthgman.dev/earthgman/snowglobe-core\";
					# Be sure to also uncomment this if you use your own nixpkgs input. Mismatched system dependencies are not good.
					# inputs.nixpkgs.follows = \"nixpkgs\";
				};
			};

			outputs = { self, nixpkgs, snowglobe-core, ... }@inputs:
			let
				lib = snowglobe-core.lib; # nixpkgs.lib merged with some custom functions used for modules.
				outputs = self.outputs;
			in
			{
				# expose hosts configured under this flake
				nixosConfigurations = import ./nixosConfigurations { inherit lib inputs outputs; };

				# expose your custom modules.
				nixosModules.default = import ./nixosModules { inherit lib inputs outputs; };

				# expose your overlays (package set modifications)
				overlays = import ./overlays { inherit inputs; };

				# your custom derivations
				packages =
				let
					supported-systems = [
						# add more system targets if you need.
						\"%s-linux\"
					];
				in
				# generate a package attribute set for each supported architecture
				lib.genAttrs supported-systems (
					system:
					import ./packages {
						pkgs = import nixpkgs {
							config.allowUnfree = true;
							inherit system;
							# give your packages access to your overlays
							overlays = builtins.attrValues outputs.overlays; # transform the set of overlays to a list
						};
					}
				);
			};
		}" "$CPU_ARCH" >$CONFIG_ROOT/flake.nix

	# nixosModules/default.nix
	printf "
    # wrapper for your custom nixosModules
		{ inputs, outputs, lib, ... }:
		{
			pkgs,
			lib,
			config,
			...
		}:
		{
			# automatically wraps up module files present in this directory
			imports = lib.importModules ./. { } ++ [
				# EXAMPLE
				# inputs.home-manager.nixosModules.default
			];

			
			# contain and enable your custom modules
			# If you wish to let your modules be consumable by other flakes, be sure to segment them to avoid conflicts.

			# options.your-name-here.enable = lib.mkEnableOption \"your-name-here's NixOS modules\";

			# apply only if your modules are enabled
			# config = lib.mkMerge [
			#		{
						# import your overlays to all hosts
						nixpkgs.overlays = builtins.attrValues outputs.overlays;
			#			your-name-here.enable = lib.mkDefault true;
			#		}
			#		(lib.mkIf config.your-name-here.enable {
			#		  your-name-here.your-module-1.enable = true;
			#		  your-name-here.your-module-2.enable = true;
			#		  ...
			#		})
			# ];
	}" | install -D /dev/stdin "$CONFIG_ROOT/nixosModules/default.nix"

	# nixosModules/profile.nix
	printf "{ pkgs, lib, config, ... }:
		{
			# you can add any configuration you want shared among all your hosts
			# Example
			# programs.ghostty.enable = true;
		}
	" | install -D /dev/stdin "$CONFIG_ROOT/nixosModules/profile.nix"

	# nixosMOdules/keyring.nix
	printf "{
	keyring = { };
}" | install -D /dev/stdin "$CONFIG_ROOT/nixosModules/keyring.nix"

	# nixosModules/nixos
	printf "# reserved for any modifications you wish to make to the core NixOS module tree from nixpkgs
		{ pkgs, lib, config, ... }:
		{
			imports = lib.importModules ./. { };
		}" | install -D /dev/stdin "$CONFIG_ROOT/nixosModules/nixos/default.nix"

	# packages
	printf "
	  # create custom derivations using pkgs.callPackage
		{ pkgs, ... }:
		{
			# my-package = pkgs.callPackage ./my-package.nix { };
		}" | install -D /dev/stdin "$CONFIG_ROOT/packages/default.nix"

	# overlays
	printf "
		# overlays are functions which modify the existing nix package set used by your flake.
		# you can use them to add, remove, or modify packages.
		{ inputs }:
		{
			# add your custom packages
			my-packages = final: prev: import ../packages {
				pkgs = final;
			};

			# example for installing rolling release of a popular project with a flake.nix
			# ghostty-git = inputs.ghostty.overlays.default;
		}" | install -D /dev/stdin "$CONFIG_ROOT/overlays/default.nix"
else
	if [ -z "$REPO_DIR" ]; then
		printf "Error: Repo not found but append mode was sepcified, this is a bug.\n"
		exit 1
	fi

	_mv_repo

	if [ -d "$HOST_CONFIG_DIR" ]; then
		rm -rf "$HOST_CONFIG_DIR"
	fi
	sed -i "/$HOSTNAME/,/^$/p" "$HOSTS_CONFIG_FILE"
fi

# sops setup
mkdir -p "$HOST_CONFIG_DIR"
printf "\nBefore configuring your user accounts, you will need to configure sops-nix.\n"
printf "By default, all nix configuration files, including those containing hashed passwords or other secrets, will be world-readable in /nix/store.\n"
printf "To circumvent this security limitation of NixOS, you can use a sops-nix configuration to encrypt part of your configuration so it can be safely stored in public repositories.\n"
printf "While other key-based encryption formats can be used for sops-nix. The installer will use age.\n\n"

SOPS_FILE="nixosConfigurations/$HOSTNAME/secrets.yaml"
KEY_FILE_PATH="/mnt/var/lib/sops-nix/keys.txt"
if [ -e "$KEY_FILE_PATH" ]; then
	rm -rf "$KEY_FILE_PATH"
fi
mkdir -p "/mnt/var/lib/sops-nix"

_create_key_alias() {
	while :; do
		printf "\nCreate an alias for your key (\`default\`, \`workstations\`, \`homelab\`, etc): "
		read -r KEY_NAME

		if [ -z "$KEY_NAME" ]; then
			printf "Key name cannot be empty.\n"
			continue
		fi

		if [ "$APPEND_MODE" ]; then
			if cat "$CONFIG_ROOT/.sops.yaml" | grep "&$KEY_NAME"; then
				printf "\nERROR: Detected duplicate key names/aliases in .sops.yaml. Your new key name must be different than your other keys.\n"
			else
				break
			fi
		else
			break
		fi
	done
}

y_or_n --msg="Do you have an exisiting age key pair that you wish to use to encrypt this host's secrets?" --default="no"

case "$yn" in
"Y" | "y")
	printf "Enter your public age key: "
	read -r PUBLIC_AGE_KEY
	_create_key_alias

	while [ ! -e "$KEY_FILE_PATH" ]; do
		printf "Place your private key file at the following location: %s\n" "$KEY_FILE_PATH"
		printf "The file must be in the proper age format or else the install will fail.\n"
		printf "press any key when the file is in place..."
		read -r some_key

		if [ -e "$KEY_FILE_PATH" ]; then
			printf "Key file was not found in the required location.\n"
		fi
	done
	;;
"N" | "n")
	# key generation
	printf "\nGenerating age key-pair...\n"
	age-keygen -o "$KEY_FILE_PATH" >/dev/null || {
		printf "Failed to generate age key pair.\n"
		exit 1
	}
	PUBLIC_AGE_KEY=$(cat "$KEY_FILE_PATH" | grep "public key:" | cut -d ":" -f2 | tr -d " ")

	_create_key_alias

	printf "The generated private key is stored at %s.\n" "$KEY_FILE_PATH"
	printf "It is imperative that you create a backup of this private key after installation is complete. If you lose it, you will no longer be able to access your secrets and your system cannot rebuild.\n"
	printf "press any key to acknowledge..."
	read -r some_key
	unset some_key
	;;
esac

if [ "$APPEND_MODE" ]; then
	# append the key and creation rules to an existing .sops.yaml
	sed -i "/keys:/a\  - &$KEY_NAME $PUBLIC_AGE_KEY" $CONFIG_ROOT/.sops.yaml
	sed -i "/creation_rules:/a\  - path_regex: $SOPS_FILE\n    key_groups:\n      - age:\n          - *$KEY_NAME" $CONFIG_ROOT/.sops.yaml
else
	printf "keys:
  - &%s %s
creation_rules:
  - path_regex: %s
    key_groups:
      - age:
          - *%s" "$KEY_NAME" "$PUBLIC_AGE_KEY" "$SOPS_FILE" "$KEY_NAME" >$CONFIG_ROOT/.sops.yaml
fi

# ensure secure permissions are set
chmod 600 "$KEY_FILE_PATH"

# write configuration files
# create configuration.nix
printf '{ pkgs, lib, config, ... }:
		{
			imports = [
				# kernel configuration from nixos-generate-config
				./hardware-configuration.nix
				# fstab config using disko modules
				./disko.nix
			];

			i18n.defaultLocale = "%s";
			services.xserver.xkb.layout = "%s";
' \
	"$LOCALE" "$XKB_LAYOUT" >"$HOST_CONFIG_DIR/configuration.nix"

if [ "$ENABLED_PROFILES" ]; then
	for profile in "${ENABLED_PROFILES[@]}"; do
		case $profile in
		"Gaming")
			printf "snowglobe-core.profiles.gaming.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
			;;
		"Office")
			printf "snowglobe-core.profiles.office.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
			;;
		"Hacking-Tools")
			printf "snowglobe-core.profiles.hacker-mode.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
			;;
		"Nix-Tools")
			printf "snowglobe-core.profiles.nix-tools.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
			;;
		"Harden")
			printf "snowglobe-core.profiles.harden.enable = true;\n" >>"$HOST_CONFIG_DIR/configuration.nix"
			;;
		esac
	done
fi
printf "}" >>"$HOST_CONFIG_DIR/configuration.nix"

_create_moduleset() {
	printf "{pkgs, lib, config, ...}:
	{
		%s = { };
	}" "$1" | install -D /dev/stdin "$HOST_CONFIG_DIR/$1/$2.nix"
}
# create split host config (programs, services)
_create_moduleset "programs" "enabled"
_create_moduleset "programs" "disabled"
_create_moduleset "services" "enabled"
_create_moduleset "services" "disabled"

# write new host to the global hosts configuration file
if [ "$APPEND_MODE" ]; then
	# with "append" remove the last character to make way for the new configuration
	sed -i '$ s/.$//' "$HOSTS_CONFIG_FILE"
else
	# add the function header if this is a new configuration
	printf "{ lib, inputs, outputs, ... }:
		{\n" >"$HOSTS_CONFIG_FILE"
fi

printf '%s = lib.mkNixosHost {
	hostname = "%s";
	cpu-vendor = "%s";
	gpu-vendors = [ %s ];
	firmware = "%s";
	isVM = %s;
	%s
	configDir = ./%s;
	sopsFile = ./%s/secrets.yaml;
	specialArgs = { inherit inputs; };
	modules = [ outputs.nixosModules.default ];
	stateVersion = "%s";
};' \
	"$HOSTNAME" \
	"$HOSTNAME" \
	"$CPU_VENDOR" \
	"$(for gpu in "${GPU_VENDORS[@]}"; do
		printf "\"%s\" " "$gpu"
	done)" \
	"$FIRMWARE" \
	"$IS_VM" \
	"$(if [ -n "$SELECTED_DESKTOP" ]; then
		printf 'desktop = "%s";' "$SELECTED_DESKTOP"
	else
		printf 'desktop = null;'
	fi)" \
	"$HOSTNAME" \
	"$HOSTNAME" \
	"$NIXOS_VERSION" >>"$HOSTS_CONFIG_FILE"

printf "\n}" >>"$HOSTS_CONFIG_FILE"

# generate hardware-configuration.nix and move disko.nix into place
_get_nixos_hardware_config

# user creation
printf "\nNow you must add and configure user accounts.\n"
printf "By default, the root user will not be accessible unless configured in this section.\n"
printf "So if you wish to add a method of authentication for root, simply type \`root\` for username.\n"
printf "Otherwise a user with the provided username will be created.\n"

printf "Similar to the base system configuration, you will be asked if you want to correct any mistakes you made.\n\n"

_set_username() {
	unset USERNAME
	unset NORMAL_USER

	printf "Note: Username will be cleansed of characters that are not [a-z][A-Z][0-9], -, or _\n"
	while :; do
		read -rp "Username: " USERNAME
		# cleanse username of problematic characters
		USERNAME=$(printf "%s" "$USERNAME" | tr -d '[`"=$%#^<>+(){}*!&[]~|][:blank:][:cntrl:]')
		if [ -z "$USERNAME" ]; then
			printf "Username cannot be empty.\n"
			continue
		else
			break
		fi
	done
	if [ "$USERNAME" != "root" ]; then
		NORMAL_USER=true
	fi
}

_set_password() {
	unset PASSWORD
	unset PASSWORD2

	while [ -z "$PASSWORD" ] || [ "$PASSWORD" != "$PASSWORD2" ]; do
		read -rs -p "Enter Password: " PASSWORD
		printf "\n"
		if [ -z "$PASSWORD" ]; then
			printf "No password provided.\n"
			if [ -z "$1" ]; then
				break
			else
				continue
			fi
		fi
		read -rs -p "Confirm Password: " PASSWORD2
		printf "\n"
		if [ "$PASSWORD" != "$PASSWORD2" ]; then
			printf "\nPasswords do not match! Try again.\n"
			continue
		fi
	done
}

# TODO
# _add_keys() {
# 	unset SSH_KEY
# 	while :; do
# 		read -rp "Enter a public SSH key: " SSH_KEY
# 		if [ -z "$SSH_KEY" ]; then
# 			printf "No SSH key was entered\n"
# 			break
# 		fi
# 	done
# }

_set_permissions() {
	USER_PERMISSIONS=()
	y_or_n --msg="Should this user have access to privilege escalation? (able to run sudo)" --default="yes" && USER_PERMISSIONS+=("Wheel")
	if [ -n "$SELECTED_DESKTOP" ]; then
		y_or_n --msg="Should this user be allowed to manage network connections?" --default="yes" && USER_PERMISSIONS+=("Networkmanager Admin")
		y_or_n --msg="Should this user be allowed to configure the CUPS printing server?" --default="yes" && USER_PERMISSIONS+=("CUPS Admin")
	fi
}

USERS=()
while :; do
	_set_username
	TMP_USERS=()
	for username in "${USERS[@]}"; do
		if [ "$USERNAME" = "$username" ]; then
			PASSWORD_ENTRY="$USERNAME""_password"
			# remove the password entry from the secrets file if this username already has configuration
			sed -i -e "s|$PASSWORD_ENTRY.*||g" -e '/^[[:space:]]*$/d' "$CONFIG_ROOT/$SOPS_FILE"
			# remove entry from the array
		else
			TMP_USERS+=("$username")
		fi
	done

	USERS=()
	for user in "${TMP_USERS[@]}"; do
		USERS+=("$user")
	done
	TMP_USERS=()

	# loop until a PASSWORD or authorized key is set for this user
	while :; do
		while [ -z "$PASSWORD" ]; do
			y_or_n --msg="Set a password for this user?" --default="yes" && {
				_set_password
				continue
			}
			break
		done

		# TODO
		# while [ -z "$AUTHORIZED_SSH_KEYS" ]; do
		# 	y_or_n --msg="Add an authorized public key to access this user over SSH?" --default="no" && {
		# 		_add_keys
		# 		continue
		# 	}
		# 	break
		# done

		if [ -z "$PASSWORD" ] && [ ${#AUTHORIZED_SSH_KEYS[@]} -lt 1 ]; then
			printf "\nError: Neither a password nor SSH key was set for this user. You will not be able to log into it unless you set one!\n\n"
		else
			break
		fi
	done

	if [ "$NORMAL_USER" ]; then
		_set_permissions
	fi

	while :; do
		clear
		printf "\nConfiguration for user: %s\n" "$USERNAME"
		if [ "$PASSWORD" ]; then
			printf "Password - =*Redacted*=\n"
		fi
		# TODO ssh keys
		if [ -z "$NORMAL_USER" ]; then
			printf "Permission - System Administrator\n\n"
		elif [ "$USER_PERMISSIONS" ]; then
			printf "Permission - %s\n" "${USER_PERMISSIONS[@]}"
		else
			printf "Permission - None\n\n"
		fi

		y_or_n --msg="Are you satisfied with the current configuration?" --default="yes" && break
		clear
		OPTIONS=("Username" "Password" "Permissions")
		SELECTED="$(for option in "${OPTIONS[@]}"; do
			printf "%s\n" "$option"
		done | fzf \
			--disabled \
			--border \
			--border-label-pos 1:bottom \
			--border-label="Which do you wish to change? (Press esc or Ctrl+C to continue)")"
		case "$SELECTED" in
		"Username")
			_set_username
			;;
		"Password")
			_set_password 'force'
			;;
		"Permissions")
			_set_permissions
			;;
		*)
			continue
			;;
		esac
	done

	USER_CONFIG_DIR="$HOST_CONFIG_DIR/users/$USERNAME"
	mkdir -p "$USER_CONFIG_DIR"

	printf "{ config, ... }:
{
	sops.secrets.%s_password.neededForUsers = true;

	users.users.%s = {
		hashedPasswordFile = config.sops.secrets.%s_password.path;
" "$USERNAME" "$USERNAME" "$USERNAME" >"$USER_CONFIG_DIR/default.nix"

	if [ "$NORMAL_USER" ]; then
		printf "isNormalUser = true;\n" >>"$USER_CONFIG_DIR/default.nix"
	fi

	if [ "$USER_PERMISSIONS" ]; then
		printf "extraGroups = [ " >>"$USER_CONFIG_DIR/default.nix"
		for permission in "${USER_PERMISSIONS[@]}"; do
			case $permission in
			"Wheel")
				printf "\"wheel\"\n" >>"$USER_CONFIG_DIR/default.nix"
				;;
			"Networkmanager Admin")
				printf "\"networkmanager\"\n" >>"$USER_CONFIG_DIR/default.nix"
				;;
			"CUPS Admin")
				printf "\"lpadmin\"\n" >>"$USER_CONFIG_DIR/default.nix"
				;;
			esac
		done
		printf "];\n" >>"$USER_CONFIG_DIR/default.nix"
	fi

	printf "};
}" >>"$USER_CONFIG_DIR/default.nix"

	USERS+=("$USERNAME")
	printf "\nConfigured Users:\n"
	for user in "${USERS[@]}"; do
		printf "%s\n" "$user"
	done
	printf "\n"
	# write to sops secrets
	printf "%s_password: %s\n" "$USERNAME" "$(mkpasswd -s "$PASSWORD")" >>"$HOST_CONFIG_DIR/secrets.yaml"

	unset USERNAME
	unset PASSWORD
	unset PASSWORD2
	unset NORMAL_USER

	y_or_n --msg="Add/Configure another user?" --default="no" || break
done

if [ -e "$CONFIG_ROOT/$SOPS_FILE" ]; then
	sops --config "$CONFIG_ROOT/.sops.yaml" -e -i "$CONFIG_ROOT/$SOPS_FILE" || {
		printf "Failed to encrypt the secrets file for this host.\n"
		exit 1
	}
fi

nixfmt.sh "$CONFIG_ROOT"

_install_nixos
